# 1. Preparing Mexico Data

In [1]:
import pandas as pd

In [2]:
#Import

df1 = pd.read_csv("data/mexico-real-estate-1.csv")
df2 = pd.read_csv("data/mexico-real-estate-2.csv")
df3 = pd.read_csv("data/mexico-real-estate-3.csv")

# Print object type and shape for DataFrames
print("df1 type:", type(df1))
print("df1 shape:", df1.shape)
print()
print("df2 type:", type(df2))
print("df2 shape:", df2.shape)
print()
print("df3 type:", type(df3))
print("df3 shape:", df3.shape)

df1 type: <class 'pandas.DataFrame'>
df1 shape: (700, 6)

df2 type: <class 'pandas.DataFrame'>
df2 shape: (700, 6)

df3 type: <class 'pandas.DataFrame'>
df3 shape: (700, 5)

In [3]:
#Insspecting our dataframe
df1.info()
df2.info()
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_usd      700 non-null    str
dtypes: float64(3), str(3)
memory usage: 32.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            571 non-null    float64
 3   lon            571 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_mxn      700 non-null    float64
dtypes: float64(4), str(2)
memory usage: 32.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            700 non-null    str
 1   place_with_parent_names  700 non-null    str
 2   lat-lon                  582 non-null    str
 3   area_m2                  700 non-null    float64
 4   price_usd                700 non-null    float64
dtypes: float64(2), str(3)
memory usage: 27.5 KB

# Clean df1

In [4]:
df1.shape

(700, 6)

In [5]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_usd      700 non-null    str
dtypes: float64(3), str(3)
memory usage: 32.9 KB

In [6]:
df1.head()

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"

In [7]:
#Remove NaN values
#inplace=True says that it drop the values in the current dataset not in a new one
df1.dropna(inplace=True)
#df1.info()

#change the strings to floats
df1["price_usd"] = (
    df1["price_usd"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "")
    .astype(float)
)

In [8]:
df1.info()

<class 'pandas.DataFrame'>
Index: 583 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  583 non-null    str
 1   state          583 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        583 non-null    float64
 5   price_usd      583 non-null    float64
dtypes: float64(4), str(2)
memory usage: 31.9 KB

# Clean df2

In [9]:
df2.shape

(700, 6)

In [10]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            571 non-null    float64
 3   lon            571 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_mxn      700 non-null    float64
dtypes: float64(4), str(2)
memory usage: 32.9 KB

In [11]:
df2.head()

  property_type       state        lat         lon  area_m2  price_mxn
0     apartment  Nuevo León  25.721081 -100.345581     72.0  1300000.0
1     apartment      Puebla        NaN         NaN    190.0  2500000.0
2         house     Morelos  23.634501 -102.552788    360.0  5300000.0
3         house     Morelos        NaN         NaN     76.0   820000.0
4         house      Puebla        NaN         NaN    200.0  1100000.0

In [12]:
#Remove NaN values (rows)
df2.dropna(inplace=True)

#Create a "price_usd" column
df2["price_mxn"] = (df2["price_mxn"] / 19).round(2)

#Drop "price_mxn" column
df2.drop(columns = ["price_mxn"], inplace=True)

df2.head()

  property_type             state        lat         lon  area_m2
0     apartment        Nuevo León  25.721081 -100.345581     72.0
2         house           Morelos  23.634501 -102.552788    360.0
6     apartment  Estado de México  19.272040  -99.572013     85.0
7         house   San Luis Potosí  22.138882 -100.996510    158.0
8     apartment  Distrito Federal  19.394558  -99.129707     65.0

# Clean df3

In [13]:
df3.shape

(700, 5)

In [14]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            700 non-null    str
 1   place_with_parent_names  700 non-null    str
 2   lat-lon                  582 non-null    str
 3   area_m2                  700 non-null    float64
 4   price_usd                700 non-null    float64
dtypes: float64(2), str(3)
memory usage: 27.5 KB

In [15]:
df3.head()

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,NaN,275.0,263432.41
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67

In [16]:
#df3["lat-lon"].head()
#drop "Nan" rows
df3.dropna(inplace=True)


#Split "lat-lon"
df3[["lat", "lon"]] = df3["lat-lon"].str.split(",", expand=True)

df3.head()

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd,lat,lon
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59,19.52589,-99.151703
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73,19.2640539,-99.5727534
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69,19.268629,-99.671722
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67,19.511938,-96.871956
5,house,|México|Jalisco|Guadalajara|,"20.689157,-103.366728",175.0,102763.00,20.689157,-103.366728

In [17]:
#Create "state" col from "place_with_parent_names"
df3["state"] = df3["place_with_parent_names"].str.split("|", expand = True)[2]

#drop columns
df3.drop(columns = ["place_with_parent_names", "lat-lon"], inplace=True)
df3.head()

,property_type,area_m2,price_usd,lat,lon,state
0,apartment,71.0,48550.59,19.52589,-99.151703,Distrito Federal
1,house,233.0,168636.73,19.2640539,-99.5727534,Estado de México
2,house,300.0,86932.69,19.268629,-99.671722,Estado de México
4,apartment,84.0,68508.67,19.511938,-96.871956,Veracruz de Ignacio de la Llave
5,house,175.0,102763.00,20.689157,-103.366728,Jalisco

# Concatenate DataFrames

In [18]:
df = pd.concat([df1, df2, df3])
print(df.shape)
df.head()

(1736, 6)

  property_type             state        lat         lon  area_m2  price_usd
0         house  Estado de México  19.560181  -99.233528    150.0   67965.56
1         house        Nuevo León  25.688436 -100.198807    186.0   63223.78
2     apartment          Guerrero  16.767704  -99.764383     82.0   84298.37
3     apartment          Guerrero  16.829782  -99.911012    150.0   94308.80
5         house           Yucatán  21.052583  -89.538639    205.0  105191.37

# Save df

In [19]:
df.to_csv("data/mexico-real-estate-clean.csv", index=False)